/**
 * Model Conversion Pipeline
 * Converts trained Keras/TensorFlow models to TFLite, ONNX, CoreML, and TF.js formats
 */

import * as fs from 'fs';
import * as path from 'path';
import { regionRegistry, loadAllRegionConfigs } from '@agrisense/region-config';

export interface ConversionConfig {
  inputModelPath: string;
  outputDir: string;
  formats: ('tflite' | 'onnx' | 'coreml' | 'tfjs')[];
  quantization?: 'none' | 'int8' | 'fp16' | 'full_int8';
  inputShape?: number[];
  optimization?: 'none' | 'latency' | 'size';
  representativeDatasetPath?: string;
  metadata?: {
    name: string;
    version: string;
    description: string;
    author: string;
    license: string;
  };
}

export interface ConversionResult {
  format: string;
  outputPath: string;
  sizeBytes: number;
  sizeMB: number;
  quantization?: string;
  latencyMs?: number;
  accuracyDrop?: number;
}

export class ModelConverter {
  private config: ConversionConfig;

  constructor(config: ConversionConfig) {
    this.config = config;
  }

  /**
   * Convert model to all specified formats
   */
  async convertAll(): Promise<ConversionResult[]> {
    const results: ConversionResult[] = [];

    for (const format of this.config.formats) {
      console.log(`\n🔄 Converting to ${format.toUpperCase()}...`);
      const result = await this.convertToFormat(format);
      results.push(result);
      console.log(`✅ ${format.toUpperCase()}: ${result.sizeMB.toFixed(2)} MB`);
    }

    return results;
  }

  /**
   * Convert to specific format
   */
  private async convertToFormat(format: string): Promise<ConversionResult> {
    switch (format) {
      case 'tflite':
        return this.convertToTFLite();
      case 'onnx':
        return this.convertToONNX();
      case 'coreml':
        return this.convertToCoreML();
      case 'tfjs':
        return this.convertToTFJS();
      default:
        throw new Error(`Unsupported format: ${format}`);
    }
  }

  /**
   * Convert to TensorFlow Lite
   */
  private async convertToTFLite(): Promise<ConversionResult> {
    const outputPath = path.join(this.config.outputDir, 'model.tflite');

    // This would use Python subprocess to run the actual conversion
    // For now, we generate the conversion script
    const script = this.generateTFLiteScript();

    const scriptPath = path.join(this.config.outputDir, 'convert_tflite.py');
    fs.writeFileSync(scriptPath, script);

    console.log(`📝 TFLite conversion script generated: ${scriptPath}`);
    console.log(`💡 Run: python ${scriptPath}`);

    return {
      format: 'tflite',
      outputPath,
      sizeBytes: 0,
      sizeMB: 0,
      quantization: this.config.quantization,
    };
  }

  /**
   * Generate TFLite conversion Python script
   */
  private generateTFLiteScript(): string {
    const quantization = this.config.quantization || 'none';
    const optimization = this.config.optimization || 'none';
    const inputShape = this.config.inputShape || [1, 224, 224, 3];

    return `#!/usr/bin/env python3
"""
TFLite Model Conversion Script
Generated by AgriSense Model Converter
"""

import tensorflow as tf
import numpy as np
import os
import sys

# Configuration
INPUT_MODEL = "${this.config.inputModelPath}"
OUTPUT_PATH = "${path.join(this.config.outputDir, 'model.tflite')}"
QUANTIZATION = "${quantization}"
OPTIMIZATION = "${optimization}"
INPUT_SHAPE = ${JSON.stringify(inputShape)}
REPRESENTATIVE_DATASET = "${this.config.representativeDatasetPath or ''}"

def load_model():
    """Load Keras model"""
    print(f"Loading model from {INPUT_MODEL}...")
    model = tf.keras.models.load_model(INPUT_MODEL)
    print(f"Model loaded: {model.name}")
    print(f"Input shape: {model.input_shape}")
    print(f"Output shape: {model.output_shape}")
    return model

def create_representative_dataset():
    """Create representative dataset for quantization"""
    if not REPRESENTATIVE_DATASET or not os.path.exists(REPRESENTATIVE_DATASET):
        print("No representative dataset provided, generating synthetic data...")
        def gen():
            for _ in range(100):
                yield [np.random.random(INPUT_SHAPE).astype(np.float32)]
        return gen

    print(f"Loading representative dataset from {REPRESENTATIVE_DATASET}...")
    # Load based on file type
    if REPRESENTATIVE_DATASET.endswith('.npz'):
        data = np.load(REPRESENTATIVE_DATASET)
        images = data['images'] if 'images' in data else data['arr_0']
    elif REPRESENTATIVE_DATASET.endswith('.npy'):
        images = np.load(REPRESENTATIVE_DATASET)
    else:
        # Assume directory of images
        import glob
        image_files = glob.glob(os.path.join(REPRESENTATIVE_DATASET, '*.jpg')) + \\
                      glob.glob(os.path.join(REPRESENTATIVE_DATASET, '*.png'))
        images = []
        for f in image_files[:100]:
            img = tf.keras.preprocessing.image.load_img(f, target_size=INPUT_SHAPE[1:3])
            img = tf.keras.preprocessing.image.img_to_array(img)
            images.append(img)
        images = np.array(images)

    images = images.astype(np.float32) / 255.0

    def gen():
        for img in images[:100]:
            yield [np.expand_dims(img, axis=0)]

    return gen

def convert_to_tflite(model):
    """Convert model to TFLite"""
    print(f"Converting to TFLite with quantization: {QUANTIZATION}")

    converter = tf.lite.TFLiteConverter.from_keras_model(model)

    # Optimization
    if OPTIMIZATION == 'latency':
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
    elif OPTIMIZATION == 'size':
        converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]

    # Quantization
    if QUANTIZATION == 'int8':
        print("Applying INT8 quantization...")
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.representative_dataset = create_representative_dataset()
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.inference_input_type = tf.uint8
        converter.inference_output_type = tf.uint8

    elif QUANTIZATION == 'fp16':
        print("Applying FP16 quantization...")
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.target_spec.supported_types = [tf.float16]

    elif QUANTIZATION == 'full_int8':
        print("Applying Full INT8 quantization...")
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.representative_dataset = create_representative_dataset()
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.inference_input_type = tf.uint8
        converter.inference_output_type = tf.uint8
        # For full int8, need to quantize input/output as well
        converter.target_spec.supported_ops = [
            tf.lite.OpsSet.TFLITE_BUILTINS_INT8,
            tf.lite.OpsSet.SELECT_TF_OPS
        ]

    # Convert
    tflite_model = converter.convert()

    # Save
    with open(OUTPUT_PATH, 'wb') as f:
        f.write(tflite_model)

    print(f"✅ Model saved to {OUTPUT_PATH}")
    print(f"📦 Model size: {len(tflite_model) / 1024 / 1024:.2f} MB")

    # Add metadata
    add_metadata(tflite_model, OUTPUT_PATH)

    return tflite_model

def add_metadata(model_bytes, output_path):
    """Add metadata to TFLite model"""
    try:
        from tflite_support.metadata_writers import image_classifier
        from tflite_support.metadata_writers import writer_utils

        print("Adding metadata...")

        # Load labels
        labels_path = os.path.join(os.path.dirname(OUTPUT_PATH), 'labels.txt')
        if os.path.exists(labels_path):
            labels = writer_utils.load_file(labels_path).decode().split('\\n')
        else:
            labels = [f'class_{i}' for i in range(100)]

        writer = image_classifier.MetadataWriter.create_for_inference(
            writer_utils.load_file(output_path),
            input_norm_mean=[127.5],
            input_norm_std=[127.5],
            labels=labels
        )

        writer_utils.save_file(writer.populate(), output_path)
        print("✅ Metadata added")
    except ImportError:
        print("⚠️ tflite-support not installed, skipping metadata")
    except Exception as e:
        print(f"⚠️ Could not add metadata: {e}")

def test_inference(model_path):
    """Test TFLite model inference"""
    print("\\n🧪 Testing inference...")
    interpreter = tf.lite.Interpreter(model_path=model_path)
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    print(f"Input: {input_details}")
    print(f"Output: {output_details}")

    # Test with random input
    input_shape = input_details[0]['shape']
    input_data = np.random.random(input_shape).astype(np.float32)

    interpreter.set_tensor(input_details[0]['index'], input_data)
    interpreter.invoke()
    output = interpreter.get_tensor(output_details[0]['index'])

    print(f"Output shape: {output.shape}")
    print(f"Output range: [{output.min():.4f}, {output.max():.4f}]")

def main():
    try:
        model = load_model()
        tflite_model = convert_to_tflite(model)
        test_inference(OUTPUT_PATH)
        print("\\n✅ Conversion complete!")
    except Exception as e:
        print(f"\\n❌ Error: {e}")
        sys.exit(1)

if __name__ == '__main__':
    main()
`;
  }

  /**
   * Convert to ONNX
   */
  private async convertToONNX(): Promise<ConversionResult> {
    const outputPath = path.join(this.config.outputDir, 'model.onnx');

    const script = this.generateONNXScript();
    const scriptPath = path.join(this.config.outputDir, 'convert_onnx.py');
    fs.writeFileSync(scriptPath, script);

    console.log(`📝 ONNX conversion script generated: ${scriptPath}`);
    console.log(`💡 Run: python ${scriptPath}`);

    return {
      format: 'onnx',
      outputPath,
      sizeBytes: 0,
      sizeMB: 0,
    };
  }

  private generateONNXScript(): string {
    return `#!/usr/bin/env python3
"""
ONNX Model Conversion Script
Generated by AgriSense Model Converter
"""

import torch
import onnx
import tensorflow as tf
import numpy as np
import os

INPUT_MODEL = "${this.config.inputModelPath}"
OUTPUT_PATH = "${path.join(this.config.outputDir, 'model.onnx')}"
INPUT_SHAPE = ${JSON.stringify(this.config.inputShape || [1, 224, 224, 3])}

def main():
    print(f"Loading TensorFlow model from {INPUT_MODEL}...")
    tf_model = tf.keras.models.load_model(INPUT_MODEL)

    # Create dummy input
    dummy_input = tf.random.normal(INPUT_SHAPE)

    # Convert using tf2onnx
    try:
        import tf2onnx
        print("Converting to ONNX...")

        onnx_model, _ = tf2onnx.convert.from_keras(
            tf_model,
            input_signature=[tf.TensorSpec(INPUT_SHAPE, tf.float32, name='input')],
            opset=13,
            output_path=OUTPUT_PATH
        )

        # Verify
        onnx_model = onnx.load(OUTPUT_PATH)
        onnx.checker.check_model(onnx_model)
        print(f"✅ ONNX model saved to {OUTPUT_PATH}")
        print(f"📦 Model size: {os.path.getsize(OUTPUT_PATH) / 1024 / 1024:.2f} MB")

        # Print model info
        print(f"Inputs: {[inp.name for inp in onnx_model.graph.input]}")
        print(f"Outputs: {[out.name for out in onnx_model.graph.output]}")

    except ImportError:
        print("❌ tf2onnx not installed. Install with: pip install tf2onnx")
        sys.exit(1)

if __name__ == '__main__':
    main()
`;
  }

  /**
   * Convert to CoreML
   */
  private async convertToCoreML(): Promise<ConversionResult> {
    const outputPath = path.join(this.config.outputDir, 'model.mlmodel');

    const script = this.generateCoreMLScript();
    const scriptPath = path.join(this.config.outputDir, 'convert_coreml.py');
    fs.writeFileSync(scriptPath, script);

    console.log(`📝 CoreML conversion script generated: ${scriptPath}`);
    console.log(`💡 Run: python ${scriptPath} (on macOS)`);

    return {
      format: 'coreml',
      outputPath,
      sizeBytes: 0,
      sizeMB: 0,
    };
  }

  private generateCoreMLScript(): string {
    return `#!/usr/bin/env python3
"""
CoreML Model Conversion Script
Generated by AgriSense Model Converter
Note: Must run on macOS with coremltools installed
"""

import coremltools as ct
import tensorflow as tf
import os
import sys

INPUT_MODEL = "${this.config.inputModelPath}"
OUTPUT_PATH = "${path.join(this.config.outputDir, 'model.mlmodel')}"
INPUT_SHAPE = ${JSON.stringify(this.config.inputShape || [1, 224, 224, 3])}

def main():
    if sys.platform != 'darwin':
        print("❌ CoreML conversion requires macOS")
        sys.exit(1)

    print(f"Loading TensorFlow model from {INPUT_MODEL}...")
    tf_model = tf.keras.models.load_model(INPUT_MODEL)

    print("Converting to CoreML...")

    # Convert
    mlmodel = ct.convert(
        tf_model,
        inputs=[ct.TensorType(shape=INPUT_SHAPE, name='input')],
        classifier_config=ct.ClassifierConfig(class_labels=[]),  # Will add labels
        minimum_deployment_target=ct.target.iOS15,
        compute_precision=ct.precision.FLOAT16,  # Use FP16 for smaller size
    )

    # Add metadata
    mlmodel.author = "AgriSense Team"
    mlmodel.license = "MIT"
    mlmodel.version = "1.0.0"
    mlmodel.short_description = "Crop disease detection model"

    # Save
    mlmodel.save(OUTPUT_PATH)
    print(f"✅ CoreML model saved to {OUTPUT_PATH}")
    print(f"📦 Model size: {os.path.getsize(OUTPUT_PATH) / 1024 / 1024:.2f} MB")

if __name__ == '__main__':
    main()
`;
  }

  /**
   * Convert to TensorFlow.js
   */
  private async convertToTFJS(): Promise<ConversionResult> {
    const outputDir = path.join(this.config.outputDir, 'tfjs');

    const script = this.generateTFJSScript();
    const scriptPath = path.join(this.config.outputDir, 'convert_tfjs.py');
    fs.writeFileSync(scriptPath, script);

    console.log(`📝 TF.js conversion script generated: ${scriptPath}`);
    console.log(`💡 Run: python ${scriptPath}`);

    return {
      format: 'tfjs',
      outputPath: outputDir,
      sizeBytes: 0,
      sizeMB: 0,
    };
  }

  private generateTFJSScript(): string {
    return `#!/usr/bin/env python3
"""
TensorFlow.js Model Conversion Script
Generated by AgriSense Model Converter
"""

import tensorflowjs as tfjs
import tensorflow as tf
import os
import sys

INPUT_MODEL = "${this.config.inputModelPath}"
OUTPUT_DIR = "${path.join(this.config.outputDir, 'tfjs')}"

def main():
    print(f"Loading TensorFlow model from {INPUT_MODEL}...")
    tf_model = tf.keras.models.load_model(INPUT_MODEL)

    print(f"Converting to TensorFlow.js format...")
    print(f"Output directory: {OUTPUT_DIR}")

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    tfjs.converters.save_keras_model(tf_model, OUTPUT_DIR)

    print(f"✅ TF.js model saved to {OUTPUT_DIR}")

    # Calculate total size
    total_size = sum(
        os.path.getsize(os.path.join(OUTPUT_DIR, f))
        for f in os.listdir(OUTPUT_DIR)
    )
    print(f"📦 Total size: {total_size / 1024 / 1024:.2f} MB")

if __name__ == '__main__':
    main()
`;
  }

  /**
   * Generate all conversion scripts at once
   */
  generateAllScripts(): void {
    fs.mkdirSync(this.config.outputDir, { recursive: true });

    const scripts = {
      'convert_tflite.py': this.generateTFLiteScript(),
      'convert_onnx.py': this.generateONNXScript(),
      'convert_coreml.py': this.generateCoreMLScript(),
      'convert_tfjs.py': this.generateTFJSScript(),
    };

    for (const [filename, content] of Object.entries(scripts)) {
      const filepath = path.join(this.config.outputDir, filename);
      fs.writeFileSync(filepath, content);
      console.log(`📝 Generated: ${filepath}`);
    }

    // Generate master script
    const masterScript = this.generateMasterScript();
    fs.writeFileSync(path.join(this.config.outputDir, 'convert_all.py'), masterScript);
    console.log(`📝 Generated master script: convert_all.py`);
  }

  private generateMasterScript(): string {
    return `#!/usr/bin/env python3
"""
Master Conversion Script
Runs all model conversions sequentially
Generated by AgriSense Model Converter
"""

import subprocess
import sys
import os

SCRIPTS = [
    ('convert_tflite.py', 'TensorFlow Lite'),
    ('convert_onnx.py', 'ONNX'),
    ('convert_coreml.py', 'CoreML (macOS only)'),
    ('convert_tfjs.py', 'TensorFlow.js'),
]

def run_script(script, name):
    print(f"\\n{'='*60}")
    print(f"Converting to {name}...")
    print(f"{'='*60}")

    try:
        result = subprocess.run([sys.executable, script], capture_output=True, text=True)
        if result.returncode == 0:
            print(f"✅ {name} conversion successful")
            print(result.stdout)
        else:
            print(f"❌ {name} conversion failed")
            print(result.stderr)
        return result.returncode == 0
    except Exception as e:
        print(f"❌ {name} error: {e}")
        return False

def main():
    print("🚀 AgriSense Model Conversion Pipeline")
    print(f"Working directory: {os.getcwd()}")

    success_count = 0
    for script, name in SCRIPTS:
        if name == 'CoreML (macOS only)' and sys.platform != 'darwin':
            print(f"\\n⏭️ Skipping {name} (not on macOS)")
            continue

        if os.path.exists(script):
            if run_script(script, name):
                success_count += 1
        else:
            print(f"⚠️ Script not found: {script}")

    print(f"\\n{'='*60}")
    print(f"Conversion complete: {success_count}/{len(SCRIPTS)} successful")
    print(f"{'='*60}")

if __name__ == '__main__':
    main()
`;
  }
}

/**
 * Batch converter for multiple regions
 */
export class BatchModelConverter {
  private regionsDir: string;
  private baseOutputDir: string;

  constructor(regionsDir: string, baseOutputDir: string) {
    this.regionsDir = regionsDir;
    this.baseOutputDir = baseOutputDir;
  }

  async convertAllRegions(formats: ConversionConfig['formats'] = ['tflite', 'onnx', 'tfjs']): Promise<void> {
    const regions = loadAllRegionConfigs(this.regionsDir);

    for (const [regionId, region] of regions) {
      console.log(`\n🌍 Processing region: ${region.name} (${regionId})`);

      const modelConfig = region.modelConfig;
      if (!modelConfig.edgeModelUrl) {
        console.log(`⚠️ No edge model URL for ${regionId}, skipping`);
        continue;
      }

      // Download model if needed
      const localModelPath = await this.downloadModel(regionId, modelConfig);
      if (!localModelPath) continue;

      const outputDir = path.join(this.baseOutputDir, regionId);
      fs.mkdirSync(outputDir, { recursive: true });

      // Copy labels
      this.copyLabels(region, outputDir);

      // Convert
      const converter = new ModelConverter({
        inputModelPath: localModelPath,
        outputDir,
        formats,
        quantization: 'int8',
        optimization: 'latency',
        metadata: {
          name: `AgriSense ${region.name} Disease Detector`,
          version: modelConfig.edgeModelVersion,
          description: `Edge model for ${region.name} crop disease detection`,
          author: 'AgriSense Team',
          license: 'MIT',
        },
      });

      converter.generateAllScripts();
    }
  }

  private async downloadModel(regionId: string, modelConfig: any): Promise<string | null> {
    // In production, download from CDN
    const localPath = path.join(this.baseOutputDir, regionId, 'model.keras');
    if (fs.existsSync(localPath)) {
      console.log(`📁 Using cached model: ${localPath}`);
      return localPath;
    }
    console.log(`⚠️ Model not found locally: ${localPath}`);
    return null;
  }

  private copyLabels(region: any, outputDir: string): void {
    const labels = region.diseases.map(d => d.id);
    const labelsPath = path.join(outputDir, 'labels.txt');
    fs.writeFileSync(labelsPath, labels.join('\n'));
    console.log(`📝 Labels saved: ${labelsPath}`);
  }
}